---
- name: Install and Start wordpress servers
  hosts: all
  become: true

  tasks:
  - name: Install httpd
    yum:
       name: httpd
       state: present
  
  - name: Install php
    yum:
       name: php
       state: present
  

  - name: Install mariadb
    yum:
       name: mariadb105-server.x86_64
       state: present
  
  - name: Install php-mysqlnd
    yum:
       name: php-mysqlnd
       state: present

  - name: Download wordpress
    get_url:
       url: "https://wordpress.org/latest.tar.gz"
       dest: "/var/www/html/"

  - name: Extract tar archieve
    command: tar -xvf /var/www/html/latest.tar.gz

  - name: Copy file from local to remote
    copy:
        src: /home/ec2-user/repo/webserver-using-terraform-ansible/wp-config.php
        dest: /var/www/html/wordpress/wp-config.php
        mode: 0644

  - name: Set ownership for WordPress directory recursively
    file:
        path: /var/www/html/wordpress
        state: directory
        recurse: yes
        owner: apache
        group: apache

  - name: Set ownership for WordPress files recursively
    file:
        path: /var/www/html/wordpress
        state: file
        recurse: yes
        owner: apache
        group: apache


  - name: Start httpd
    service:
      name: httpd
      state: started
      enabled: yes
