---
- name: Install and Start wordpress servers
  hosts: all
  become: true

  tasks:
  - name: Perform yum update
    ansible.builtin.yum:
       name: '*'
       state: latest
    
  - name: Install httpd
    yum:
       name: httpd
       state: present
  
  - name: Install php
    yum:
       name: php
       state: present
  

  - name: Install mariadb
    yum:
       name: mariadb105-server.x86_64
       state: present
  
  - name: Install php-mysqlnd
    yum:
       name: php-mysqlnd
       state: present

  - name: Download wordpress
    get_url:
       url: "https://wordpress.org/latest.tar.gz"
       dest: "/home/ec2-user/"

  - name: Extract tar archieve
    command: tar -xvf /home/ec2-user/wordpress-6.4.3.tar.gz
  
  - name: Move wordpress to apache  
    command: mv wordpress/* /var/www/html/

  - name: Copy file from local to remote
    copy:
        src: /home/ec2-user/repo/webserver-using-terraform-ansible/wp-config.php
        dest: /var/www/html/wp-config.php
        mode: 0644

  - name: Set ownership for WordPress directory recursively
    file:
        path: /var/www/html
        state: directory
        recurse: yes
        owner: apache
        group: apache
 
  - name: Set permissions to wp-content
    file:
        path: /var/www/html/wp-content
        mode: "755"
        
  - name: Start httpd
    service:
      name: httpd
      state: started
      enabled: yes
